openapi: "3.0.0"
info:
  version: 0.0.1
  title: Test
paths:
  /users:
    get:
      summary: List all users
      tags:
        - "User"
      description: Desc
      operationId: listUsers
      responses:
        "200":
          description: Description
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDto'
components:
  schemas:
    UserDto:
      type: object
      required:
        - userName
        - password
        - balance
      properties:
        id:
          type: integer
        userName:
          type: string
        password:
          type: string
        balance:
          type: integer
        address:
          type: string