version: '3.3'
services:
  db:
    container_name: mysql
    image: mysql
    networks:
      - localhost
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'

  app:
    image: docker.io/library/single-endpoint:0.0.1-SNAPSHOT.rabbitmq
    depends_on:
      - db
    networks:
      - localhost
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/test?autoReconnect=true&allowPublicKeyRetrieval=True&useSSL=false'
      SPRING_RABBITMQ_HOST: 'rabbitmq'
      SERVER_PORT: 8081
      RABBITMQ_USER_QUEUE: Default
    ports:
      - '8081:8081'
  listener:
    image: docker.io/library/listener:0.0.1-SNAPSHOT
    networks:
      - localhost
    environment:
      SPRING_RABBITMQ_HOST: 'rabbitmq'
      SERVER_PORT: 8082
      RABBITMQ_USER_QUEUE: Default
    ports:
      - '8082:8082'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - localhost
networks:
  localhost:
    driver: bridge
